//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        public int MetodoPagoID { get; set; }
        public string MetodoPago1 { get; set; }
        public string EstadoPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Detalles { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
